version: '2'
services:
  gatherme_communities_ms2:
    container_name: gatherme_communities_ms
    build: .
    command: bundle exec rails s -e development -p 3009 -b '0.0.0.0'
    volumes:
      - .:/gatherme_communities
    ports:
      - "3009:3009"

